### PR TITLE
Close DB connection at the end of each CSM load test transaction.

### PR DESCRIPTION
**Pull request by doctoryes**
@cpennington @alawibaba Simple change - please review.

### CODE REVIEW

**Comment by cpennington** [comment]
Does django automatically open a connection when it's first used? (I assume it must, based on this change still working).

**Comment by doctoryes** [comment]
I was unsure at first as well. But it must, since this change does indeed appear to work.

**Comment by doctoryes** [comment]
@cpennington @alawibaba I'd like to get this reviewed and merged.

**Comment by cpennington** [comment]
:+1:

**Pull request merged**
