### PR TITLE
update factory-boy

### PR DESCRIPTION
**Pull request by muhammad-ammar**

### CODE REVIEW

**Comment by muhammad-ammar** [comment]
@cpennington Can you please look into this? Thanks!

**Comment by muhammad-ammar** [comment]
@wedaly

**Comment by muhammad-ammar** [comment]
@wedaly @macdiesel @symbolist @muzaffaryousaf Please have a look. Thanks

**Comment by macdiesel** [comment]
:+1:

**Comment by symbolist** [comment]
:+1:

**Pull request merged**
