### PR TITLE
Added loadtests for devstack

### PR DESCRIPTION
**Pull request by clintonb**

### CODE REVIEW

**Comment by clintonb** [comment]
@efagin @robrap @feanil @staubina @gsong @jzoldak @cpennington please review and/or recommend additional tests.

**Comment by clintonb** [comment]
@edx/testeng please review

**Comment by benpatterson** [comment]
@pwnage101 could you take a look?

**Comment by robrap** [comment]
@feanil Have you brought your comment to @pwnage101's attention for the general LMS tests, etc.?    Either way, I guess I'm doing that now. :)

**Comment by pwnage101** [comment]
For organizational reasons, I have concerns about putting loadtest helper modules in `util/` which traditionally houses scripts and other modules which aren't imported by any of the loadtests.  Can you move `util/mixins.py` to `helpers/mixins.py`?

**Comment by clintonb** [comment]
@pwnage101 I have moved the mixins. Let me know if you have any other feedback.
@feanil I agree that we should exercise the full logistration flow in general. For these specific tests, I just wanted to ensure Docker-based devstack will sustain our needs for development, which don't necessarily involve frequent logins.

**Comment by pwnage101** [comment]
@clintonb LGTM

**Pull request merged**
