### PR TITLE
ECOM-3619 weight added in locust tasks

### PR DESCRIPTION
**Pull request by tasawernawaz**
I have added `weight=10` for 
* list endpoint which will be called from learner dashboard.
* credential rendering.

@awais786 @zubair-arbi @ahsan-ul-haq

### CODE REVIEW

**Comment by tasawernawaz** [comment]
@clintonb Does this makes sense to add weights for list endpoint and credential rendering. I believe both of these endpoints will hit more frequently.

**Comment by clintonb** [comment]
Let's walk through all of the scenarios:

1. Create/issue a credential after a user completes a course.
2. Re-issue a credential after a "re-run" of credentials.
3. Get a list of all credentials to populate the student dashboard.
4. View a single credential after following a link from the dashboard, email, etc.

We will ignore the use case of creating a certificate because it doesn't occur enough to matter and you have no tests for it anyway.

We issue far fewer credentials than we have students. Of the credentials we issue, the likelihood of updating a credential is somewhat low. Thus, those actions have the lowest weight (1).

Without looking at any real-world data, I would guess the student dashboard is loaded more often than a credential. How much more often depends on the data, which you should pull from New Relic. That will determine more adequate weights for those calls. 10x (compared to the create credential call) seems very low, and might result in an incorrectly high throughput.

Also, note that if rendering the credential also retrieves the data from the DB, you don't need to increase the weight of `get_credential`. That API endpoint would not be used in a normal usage scenario, as the data would be rendered server-side.

**Comment by tasawernawaz** [comment]
@clintonb We have fixtures in both programs service and credential service for setup. 
* Programs fixture will add a Demo Program that contains edX Demo Course. 
* Credential fixture create certificate configuration in credential service which will be assigned to users returned by auto_auth().

You are right about adding more weight on List endpoint of API.

**Comment by tasawernawaz** [comment]
@clintonb I have looked into New Relic. We have 200rpm for learner dashboard and 2rpm for viewing web certificate, so I think its is 1:100 ratio for rendering and listing endpoint.

**Comment by clintonb** [comment]
Sounds good to me. :+1: once those weights are added here.

**Comment by tasawernawaz** [comment]
@clintonb Just want to confirm that should I add 10 to render and 1000 to list endpoint or 1 to render and 100 to list.

**Comment by cpennington** [comment]
@tasawernawaz: What do you think is more representative of the load that the service will be under.

**Comment by tasawernawaz** [comment]
@cpennington List endpoint is our main focus while testing load because it will be called every time dashboard will be called. Since ratio between rendering and list endpoint is 1:100, I am adding 10 to rendering and 1000 to list endpoint.

**Pull request merged**
