### PR TITLE
MA-2696: load test new index for unread_comment_count

### PR DESCRIPTION
**Pull request by wajeeha-khalid**
[MA-2696](https://openedx.atlassian.net/browse/MA-2696)

Run load tests on a new index to calculate `unread_comment_count`.
`db.contents.ensureIndex({ comment_thread_id: 1, author_id: 1, created_at: 1 }, { background: true })`

### CODE REVIEW

**Comment by pwnage101** [comment]
@wajeeha-khalid I thought there was one index added and one removed (recalling a previous conversation we had), but this change only adds an index.  Maybe I was thinking about a different change?

**Comment by wajeeha-khalid** [comment]
@pwnage101 Thats true; I have not added remove index to this PR yet (or more specifically `discussions_api/db/create_indexes.js`); because we intend to keep old index as is (for some time) in case we want to rollback.
So, I explicitly asked devops to add new index and remove old one on server deployment ticket. Which means the tests were run according to what you assume; one index added one removed; and the load test server has the same state.

Reference: https://openedx.atlassian.net/servicedesk/customer/portal/3/DEVOPS-4656

**Comment by pwnage101** [comment]
:+1:

**Comment by feanil** [comment]
Closing due to age.

**Pull request closed without merging**
