### PR TITLE
Upgrade numpy to it's latest version

### PR DESCRIPTION
**Pull request by muzaffaryousaf**
We need to upgrade this to keep the numpy versions in-sync across different repos. 
Platform PR: https://github.com/edx/edx-platform/pull/12444

### CODE REVIEW

**Comment by muzaffaryousaf** [comment]
@nedbat @andy-armstrong Would you mind to give it a look.

**Comment by muzaffaryousaf** [comment]
@andy-armstrong @nedbat Different version in this repo would't complaint about VersionConflict, Do you think we should update the version here ?

**Comment by andy-armstrong** [comment]
@muzaffaryousaf I'm not sure. @tasawernawaz can you advise.

**Comment by muzaffaryousaf** [comment]
We don't need to upgrade this one either.

**Pull request closed without merging**
