### PR TITLE
TNL-4937: Set up indexes for load testing.

### PR DESCRIPTION
**Pull request by robrap**
This can be used to set up indexes for load testing.  

I'm punting on the larger question of getting migrations set up in the comment service because we are considering a move to mysql.  Once this gets settled, we can determine whether this effort is warranted.

For now, this script is being added to the edx-load-tests repo so we can make progress on the performance testing that will help us make appropriate decisions.

FYI:
@ormsbee 
@dianakhuang 
@jibsheet 
@e0d

### CODE REVIEW

**Comment by robrap** [comment]
@benpatterson @jzoldak: FYI: I set up this new PR and the single check was never set up.

**Comment by robrap** [comment]
FYI: @BenjiLee

**Comment by jzoldak** [comment]
@robrap what do you mean by the single check was never set up?

**Comment by robrap** [comment]
@jzoldak: here is another pr for this repo with Travis CI check: https://github.com/edx/edx-load-tests/pull/55

I'll amend and push to see if it fixes.

**Comment by jzoldak** [comment]
@robrap The travis config file for this repo is set up to only run tests for PRs that are against master. Since this is against your other branch, you would need to add that to the config. See [.travis.yml#L18](../blob/master/.travis.yml#L18).

**Comment by robrap** [comment]
@jzoldak:  Cool.  Thank you for explaining.

**Comment by robrap** [comment]
FYI: @tobz @pwnage101

**Pull request merged**
